import "./globals.css";
import Image from "next/image";

import { Raleway } from 'next/font/google';


const raleway = Raleway ({
  subsets: ['latin'],
  weights: ['400', '700'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  
      <body
        className={raleway.className}
      >
        <Image src={"/Layout.jpeg"} height={2000} width={2000} alt='Fondo'
        className="h-screen w-screen absolute z-0"/>
        <div className="relative z-1">
          {children}
        </div>
        
      </body>
      
    </html>
  );
}
